version: '3.8'

services:
  model_v1:
    build: ./model_v1
    container_name: titanic_model_v1
    ports:
      - "5001:5000"

  model_v2:
    build: ./model_v2
    container_name: titanic_model_v2
    ports:
      - "5002:5000"
  nginx:
    image: nginx:latest
    container_name: nginx_ab
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - model_v1
      - model_v2
  dashboard:
    build:
      context: ./dashboard
    container_name: ab_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./model_v1/predictions.log:/logs/model_v1.log:ro
      - ./model_v2/predictions.log:/logs/model_v2.log:ro
