name: Canary Deploy Models

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Docker Images
        run: |
          docker build -t iris_model_v1 ./iris_canary_deploy/model_v1
          docker build -t iris_model_v2 ./iris_canary_deploy/model_v2
          docker build -t iris_model_v3 ./iris_canary_deploy/model_v3
          echo "Images built. Push to ECR or DockerHub next step..."


